name: docker
on:
  push:
    branches:
      - staging

jobs:
  indocker:
    name: Run job in docker
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - run: |
          node -v
      - name: setup cf cli
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
          echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" > /etc/apt/sources.list.d/cloudfoundry-cli.list
          apt-get update
          apt-get install cf8-cli
          cf -v