name: docker
on:
  push:
    branches:
      - staging

jobs:
  indocker:
    name: Run job in docker
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - run: |
          pwd
          ls -l 