name: docker
on:
  push:
    branches:
      - staging

jobs:
  indocker:
    name: Run job in docker
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
    - name: git
      run: |
        git branch
        git checkout staging
        ls -l cap