name: Build & deploy the app
on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Job to build the cap app
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install MBT build tool
      run: npm install -g mbt
    - name: Build MTA Archive
      run : cd cap && npm run build

    - name: Deploy to CF
      run: echo "Deploying to CF next"