name: Build and deploy the app
on:
  push:
    branches:
      - staging

jobs:
  build:
    name: build the app
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: install mbt build tool
      run: npm install -g mbt
    - name: install dependencies
      run: |
        npm install -g mbt
        npm install --production
        mbt --version
    - name: greet me
      run : echo "hi there, how is it going?"