name: Update the names
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            ref: main
      - run: |
          git status
          gh --version
      - name: add name and commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git ls-remote --exit-code --heads origin auto-update-names; then
            git fetch origin auto-update-names
            git checkout auto-update-names
          else
            git checkout -b auto-update-names
          fi
          echo "Peter" >> names
          git add names && git commit -m "Add name to names file"
          git push -u origin auto-update-names
          if ! gh pr view mybranch > /dev/null 2>&1; then
            gh pr create --title "latest update to names" --body "auto update" --base main
          fi
