name: Update the names
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            ref: main
            # let's have some commit history to work with
            fetch-depth: 0
      - name: add name and commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b auto-update-names
          git status
          echo "Peter" >> names
          git add names && git commit -m "Add name to names file"
          git push --set-upstream origin auto-update-names

      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: auto-update-names
          PULL_REQUEST_BRANCH: main